language: objective-c
osx_image: xcode7
install:
- gem install xcpretty cocoapods --no-rdoc --no-ri --no-document --quiet
script:
- pod install
- set -o pipefail ; xcodebuild test -workspace ClarifaiApiDemo.xcworkspace -scheme ClarifaiApiDemo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 5,OS=9.0' | xcpretty -c
